import { useTranslation } from "react-i18next";



export default function TermsAndConditions() { 
    const { t } = useTranslation();
    return (  
        <div className="bg-linkIt-500 p-[7%] pt-[17vh] lg:pt-[23vh]">
            <h1 className="titles-size text-center font-bold font-manrope">{t('Términos y condiciones de LinkIT')}</h1>
            <p className="text-size font-montserrat my-[2%]">{t('En LinkIT creemos que es esencial la transparencia al momento de relacionarnos con terceros. Por eso, es muy importante que leas y entiendas estos términos y condiciones (los “TyC”) porque son las bases de cómo nos relacionamos con todos los visitantes y usuarios (los “Usuarios”) del sitio web www.linkit-hr.com (en adelante “el Sitio Web”), de las aplicaciones móviles de LinkIT y de todos los servicios que puedas contratar y programas de estudio a los que puedas acceder por esos medios con Linkit (los “Servicios”).')} <br /> <br />

{t('Utilizar el Sitio Web y/o cualquiera de los Servicios implica que, como Usuario, aceptás estos TyC y, en consecuencia, quedás obligado por todas las disposiciones de abajo. La aceptación de los presentes TyC, implica asimismo la aceptación expresa de las Política de Privacidad que es parte integrante de éstos.')}
 </p>

 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Capacidad')}</h2>
 <p className="text-size font-montserrat my-[2%]"> {t('Como Usuario declarás que tienes plena capacidad legal para contratar de acuerdo con las leyes del país donde residas. De no ser así, debes abstenerte de navegar por el Sitio Web y de requerir la contratación de cualquiera de los Servicios. La continuidad en el Sitio Web por aquellos que no cumplan este requisito, será bajo su propia responsabilidad y/o de aquél a quien estuviera a su cargo.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Registro y envío de postulación')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('Aquellos Usuarios que deseen postularse a las vacantes brindadas por LinkIT, deberán completar los formularios que para cada caso provee el Sitio Web y/o LinkIT por cualquier medio. Los Usuarios reconocen que la información allí provista tiene el carácter de declaración jurada, por lo que quedan comprometidos a brindar sus datos personales así como los de aquellas personas físicas o jurídicas que propusiera como garantes en forma completa y correcta. Los datos personales recabados por LinkIT serán tratados de acuerdo con la Política de Privacidad. Las postulaciones son de carácter personal, por lo que ningún Usuario deberá presentar postulaciones en nombre o con información de terceros, con o sin su autorización. Además, en ningún caso el Usuario podrá utilizar una dirección de correo electrónico falsa o de algún modo engañar a LinkIT o a otros miembros en cuanto a su identidad o al origen de un mensaje o contenido. Al enviar la postulación, el usuario autoriza expresamente a LinkIT a verificar su información personal. Asimismo, declara bajo juramento que aquellas personas indicadas como garantes han prestado la misma autorización, asumiendo irrevocablemente la responsabilidad por cualquier daño, perjuicio o responsabilidad jurídica o legal que pudiera originar a LinkIT y/o terceros, sin limitación. El uso indebido de información de terceros de los que no tuviera autorización suficiente será bajo la exclusiva responsabilidad del Usuario, que en su caso responderá por ello tanto ante LinkIT y las personas físicas o jurídicas cuya información hubiese suministrado sin autorización o indebidamente. Tu solicitud podría o no ser aceptada, lo que queda a criterio exclusivo de LinkIT. El simple envío de tu solicitud de ningún modo es vinculante para LinkIT. Las postulaciones se analizan en función de la información provista en los formularios por lo que la inexactitud o parcialidad material de cualquiera de los datos indicados allí podría generar el rechazo de tu postulación, incluso luego de aceptada y/o de iniciado el programa de estudios al que fuiste aceptado. Sin perjuicio de la información y documentación enviada por el Usuario al momento de completar y enviar el formulario, LinkIT podrá solicitar la presentación de información y/o elementos adicionales que considere necesarios para corroborar adecuadamente la información suministrada y evaluar tu postulación.Al enviar el formulario prestas tu conformidad para recibir en la casilla de correo electrónico consignada, información, promociones, publicidad y cualquier otra información de LinkIT.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Proceso de Postulaciones')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('El usuario garantiza la autenticidad de toda la documentación acompañada -digital o físicamente en cualquier formato y soporte- que LinkIT le solicite por haber sido aceptada su postulación o, previo a ello, para el análisis de la misma.Una vez recibida la postulación, el Usuario podría ser citado para una entrevista personal u online. En ese caso, asumís el compromiso de presentarte a la entrevista con toda la información y documentación remitida previamente en forma digital para el supuesto en el LinkIT necesite analizarla presencialmente. LinkIT se compromete a analizar la postulación del Usuario dentro de los 45 días corridos de recibida. Los Usuarios que sean aceptados para sus postulaciones podrán remitir a LinkIT, dentro de los 10 (diez) días hábiles de aceptada su postulación, su propuesta para el pago del programa de estudio al que han sido aceptados junto con la documentación relevante para dicha propuesta de pago. Cada propuesta de pago deberá ser formulada y mantenida por el Usuario en una determinada moneda y/o unidad de medida y no corresponderá en ningún caso su actualización y/o mantenimiento expresado en ninguna moneda ni unidad de medida diferente a aquella en que fuera propuesta. El Usuario se considerará plenamente aceptado al programa de estudio una vez que LinkIT acepte su conformidad con la propuesta de pago presentada por el Usuario. El Usuario reconoce que LinkIT no es una entidad de crédito sino de carácter educativo. Asimismo, el Usuario reconoce que los programas de estudio dictados en LinkIT son de modalidad tiempo completo y que es su responsabilidad procurar los tiempos necesarios para la asistencia a clases y prácticas. En ningún caso, la aceptación de su postulación implicará de parte de LinkIT una invitación a renunciar a otras obligaciones laborales o sociales.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Compromiso del Usuario')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('Como Usuario te comprometes a: (i) no realizar actos que impliquen riesgos para el Sitio Web y/o la aplicación y/o tiendan a apropiarse de sus técnicas y/o contenidos. (ii) no utilizar ningún tipo de robot, araña (spider), gusanos, troyanos ni ningún otro medio automático o manual tendiente a monitorear o copiar la información contenida. (iii) no utilizar software, hardware, malware ni ningún otro método con el objeto de interferir y/o intervenir la correcta funcionalidad del Sitio Web. (iv) no utilizar ningún método manual ni automático a efectos de interceptar, duplicar, revelar y en definitiva acceder a la información que a través del Sitio Web se envía, con cualquier fin. Todo ello, con la excepción de aquellos casos en que expresamente fuera autorizado por LinkIT a tales efectos y en los términos en que fuera conferida dicha autorización. En caso de incumplimiento de los compromisos arriba listados, LinkIT se reserva el derecho de suspender al Usuario inmediatamente para acceder y/o utilizar el Sitio Web y los Servicios, ya sea de forma temporal o definitiva y/o la cancelación de su registración como usuario y/o el bloqueo de su dirección IP para acceder al Sitio Web y en definitiva, cualquier medida tendiente a preservar y garantizar la seguridad de funcionamiento del Sitio Web y de la información contenida. Asimismo, una vez aceptada la postulación del Usuario al programa de estudio, éste no utilizará ninguno de los medios de comunicación puestos a su disposición por LinkIT para transmitir, mostrar, ejecutar o de algún modo poner a disposición mensajes, contenidos o materiales (i) que sean ilegales, obscenos, amenazantes, masivos no solicitados o “spam”, difamatorios, invasores de la privacidad, o (ii) que violen o infrinjan derechos de autor, marcas registradas, patentes, secretos comerciales y otros derechos de propiedad intelectual, derechos de privacidad o publicidad, reglamentos o estatutos de comunicaciones, o cualesquiera otras leyes, incluyendo, sin limitación, las leyes sobre difamación, acoso, obscenidad y pornografía; o (iii) que constituyan campañas políticas o solicitudes de venta o marketing o que contengan virus informáticos u otro código de computadora destinado a interferir con la funcionalidad de los sistemas de computadoras. Durante la vigencia del programa de estudio, se espera que los Usuarios se comporten de una manera adecuada y respetuosa, teniendo en cuenta un alto estándar de educación y progresión de carrera para con las otras personas.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Responsabilidad De LinkIT')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('LinkIT se responsabiliza por la recolección, almacenamiento y tratamiento de toda la información personal proporcionada por el usuario solicitante, de conformidad con lo dispuesto en los presentes términos y condiciones y la Ley 25.326Si bien LinkIT adopta medidas de seguridad para mantener la disponibilidad de los Servicios, es posible que en algún momento el Sitio Web y/o cualquiera de las plataformas por las que se prestan los Servicios no se encuentren disponibles. Esto puede ocurrir debido a tareas de mantenimiento programadas o por inconvenientes operativos. El Usuario renuncia a cualquier derecho o acción vinculados con la falta de disponibilidad de los Servicios y/o del Sitio Web, incluyendo sin limitarse, cualquier reclamo referente a la compensación de daño directo o eventual y lucro cesante por la falta de disponibilidad de los mismos. LinkIT tampoco será responsable por la demora o rendimiento defectuoso del Sitio Web o de cualquiera de los Servicios a raíz de situaciones fuera de nuestra capacidad de control, entendido este concepto en términos razonables, incluyendo entre otros eventos interrupciones en el suministro eléctrico y de Internet o las telecomunicaciones, o bien restricciones gubernamentales. LinkIT no asume ninguna responsabilidad adicional a las que se establecen expresamente a su cargo en éstos TyC y la Política de Privacidad, excluyéndose –aunque no limitadamente- específicamente a (i) la responsabilidad por publicidad de terceros que pudiera contener el Sitio Web y/o los vínculos que el Usuario establezca con ellos y/o otros usuarios (ii) la responsabilidad por eventuales daños y/o perjuicios que pudieran emerger de fallas en el sistema, servidor o servicio de internet en oportunidad del acceso y/o utilización del Servicio bajo cualquier modalidad que el Usuario empleara.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Propiedad Intelectual')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('Todo el contenido del sitio web: www.linkit-hr.com pertenece a LinkIT incluyendo -aunque no limitadamente- logotipos, diseños, dibujos, estudios, marcas comerciales y en particular, la aplicación. En consecuencia, todo lo comprendido tanto a la vista del usuario como el software controlador se encuentra protegido por la normativa local e internacional en materia de protección de derechos de autor, marcas y patentes. De igual forma, el contenido de los programas de estudio, componentes didácticos, forma de presentación y exposición, así como la metodología de enseñanza y todos los desarrollos ocurridos durante o en ocasión de los programas de estudio son de titularidad de LinkIT y cuentan con las protecciones referidas arriba. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones particularmente estipuladas en estos TyC harán pasible a su responsable de las acciones legales pertinentes.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Otras Disposiciones')}</h2>
<p className="text-size font-montserrat my-[2%]">{t('En el caso que cualquiera de las disposiciones de estos TyC fuese declarada nula por la autoridad competente que correspondiera, ello no afectará en ningún modo las restantes cláusulas que no hubieran sufrido la sanción y mantendrán su vigencia integralmente. La demora de LinkIT en ejercer sus derechos o el no ejercerlos, no implica que LinkIT renuncie a los derechos incluidos en estos TyC. Sólo podría entenderse que LinkIT renunció a cualquiera de sus derechos si lo comunica expresamente y, de hacerlo, sólo se entenderá que renuncia a ese derecho en particular.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Vigencia')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('Estos TyC se actualizaron por última vez el 11 de diciembre de 2022. LinkIT se reserva el derecho de modificar los presentes TyC en cualquier momento ya sea para ajustarlos a su giro comercial, nuevos requerimientos legales, técnicos, tecnológicos y toda otra circunstancia que a criterio de LinkIT amerite su actualización. Los cambios serán informados por correo electrónico a los usuarios registrados. El uso continuado del sitio y los servicios que contiene, luego de su modificación, importará el consentimiento del usuario a las nuevas disposiciones.')}</p>
 <h2 className="subtitles-size font-bold font-montserrat text-linkIt-300"> {t('Jurisdicción Y Competencia')}</h2>
 <p className="text-size font-montserrat my-[2%]">{t('Toda controversia derivada de, o relacionada a, éstos TyC, su existencia, validez, interpretación, alcance o cumplimiento y en general, toda desavenencia que no pudiera ser resuelta mediante acuerdo privado de las partes involucradas, será sometida a la jurisdicción y competencia de los Tribunales Ordinarios en lo Comercial con asiento en la Ciudad Autónoma de Buenos Aires. La aceptación de estos TyC importará la renuncia a cualquier fuero o jurisdicción que pudiera corresponder.')}</p>
        </div>
      )
}